import { AnimationMode, SimulationParams } from './types';

export const DEFAULT_PARAMS: SimulationParams = {
  density: 2000,
  speed: 1.6,
  vertical: 1.6,
  tailAmp: 0.25,
  tailFreq: 6.0,
  bands: 5,
  jitter: 0.12,
  fishScale: 1.0,
  palette: 'natural',
  geometry: 'organic', // Default to realistic 3D
  mode: AnimationMode.MURMURATION,
  stereo: false,
  hologram: false,
};

export const PRESETS: Record<string, Partial<SimulationParams>> = {
  calm: {
    mode: AnimationMode.SCHOOL,
    density: 1500,
    speed: 1.0,
    vertical: 1.2,
    tailAmp: 0.18,
    tailFreq: 4.5,
    bands: 4,
    jitter: 0.06,
    fishScale: 1.0,
    palette: 'natural',
    geometry: 'organic',
    hologram: false,
  },
  murmur: {
    mode: AnimationMode.MURMURATION,
    density: 2500,
    speed: 1.6,
    vertical: 1.6,
    tailAmp: 0.25,
    tailFreq: 6.0,
    bands: 5,
    jitter: 0.12,
    fishScale: 1.0,
    palette: 'natural',
    geometry: 'organic',
    hologram: false,
  },
  storm: {
    mode: AnimationMode.TURBULENCE,
    density: 3500,
    speed: 2.6,
    vertical: 2.2,
    tailAmp: 0.32,
    tailFreq: 8.0,
    bands: 6,
    jitter: 0.18,
    fishScale: 0.9,
    palette: 'neon',
    geometry: 'voxel', // Voxel shapes for storm
    hologram: true,
  },
  columns: {
    mode: AnimationMode.COLUMNS,
    density: 2200,
    speed: 1.8,
    vertical: 2.4,
    tailAmp: 0.28,
    tailFreq: 7.0,
    bands: 5,
    jitter: 0.10,
    fishScale: 1.1,
    palette: 'sunset',
    geometry: 'organic',
    hologram: false,
  },
  matrix: {
    mode: AnimationMode.DNA,
    density: 2500,
    speed: 1.2,
    vertical: 2.5,
    tailAmp: 0.15,
    tailFreq: 5.0,
    bands: 8,
    jitter: 0.25,
    fishScale: 0.8,
    palette: 'cyber',
    geometry: 'voxel', // Cyber look
    hologram: true,
  },
  galaxy: {
    mode: AnimationMode.SPIRAL,
    density: 4000,
    speed: 0.8,
    vertical: 0.5,
    tailAmp: 0.2,
    tailFreq: 3.0,
    bands: 10,
    jitter: 0.4,
    fishScale: 0.6,
    palette: 'spectral',
    geometry: 'voxel',
    hologram: false,
  },
  void: {
    mode: AnimationMode.ACCRETION,
    density: 5000,
    speed: 1.5,
    vertical: 1.0,
    tailAmp: 0.1,
    tailFreq: 2.0,
    bands: 2,
    jitter: 0.05,
    fishScale: 0.5,
    palette: 'cherry',
    geometry: 'organic',
    hologram: true,
  },
  topology: {
    mode: AnimationMode.KLEIN,
    density: 3000,
    speed: 0.6,
    vertical: 2.0,
    tailAmp: 0.2,
    tailFreq: 4.0,
    bands: 1,
    jitter: 0.0,
    fishScale: 0.8,
    palette: 'neon',
    geometry: 'voxel',
    hologram: false,
  },
  alien: {
    mode: AnimationMode.SUPERSHAPE,
    density: 4500,
    speed: 0.4,
    vertical: 1.2,
    tailAmp: 0.3,
    tailFreq: 8.0,
    bands: 8,
    jitter: 0.3,
    fishScale: 0.7,
    palette: 'spectral',
    geometry: 'organic',
    hologram: true,
  }
};